name: 'Job summary'
description: 'Easily add a job summary'
author: 'Jaz White'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  summary:
    description: 'Your markdown summary'
    required: true

runs:
  using: node20
  main: dist/index.js
