name: Job summary
description: Easily add a summary to your job
author: Jaz White

branding:
  icon: align-justify
  color: blue

inputs:
  summary:
    description: Your markdown summary
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "${{ inputs.summary }}" >> $GITHUB_STEP_SUMMARY
